//
//  Meal+inject.swift
//
//
//  Created by Tanner Severson on 6/23/24.
//

import Foundation

@testable import Meals_Models

extension Meal {
    
    static func inject(
        idMeal: String? = nil,
        strMeal: String? = nil,
        strCategory: String? = nil,
        strArea: String? = nil,
        strInstructions: String? = nil,
        strTags: String? = nil,
        strIngredient1: String? = nil,
        strIngredient2: String? = nil,
        strIngredient3: String? = nil,
        strIngredient4: String? = nil,
        strIngredient5: String? = nil,
        strIngredient6: String? = nil,
        strIngredient7: String? = nil,
        strIngredient8: String? = nil,
        strIngredient9: String? = nil,
        strIngredient10: String? = nil,
        strIngredient11: String? = nil,
        strIngredient12: String? = nil,
        strIngredient13: String? = nil,
        strIngredient14: String? = nil,
        strIngredient15: String? = nil,
        strIngredient16: String? = nil,
        strIngredient17: String? = nil,
        strIngredient18: String? = nil,
        strIngredient19: String? = nil,
        strIngredient20: String? = nil,
        strMeasure1: String? = nil,
        strMeasure2: String? = nil,
        strMeasure3: String? = nil,
        strMeasure4: String? = nil,
        strMeasure5: String? = nil,
        strMeasure6: String? = nil,
        strMeasure7: String? = nil,
        strMeasure8: String? = nil,
        strMeasure9: String? = nil,
        strMeasure10: String? = nil,
        strMeasure11: String? = nil,
        strMeasure12: String? = nil,
        strMeasure13: String? = nil,
        strMeasure14: String? = nil,
        strMeasure15: String? = nil,
        strMeasure16: String? = nil,
        strMeasure17: String? = nil,
        strMeasure18: String? = nil,
        strMeasure19: String? = nil,
        strMeasure20: String? = nil,
        strMealThumb: String? = nil,
        dateModified: String? = nil
    ) -> Meal {
        .init(
            idMeal: idMeal,
            strMeal: strMeal,
            strCategory: strCategory,
            strArea: strArea,
            strInstructions: strInstructions,
            strTags: strTags,
            strIngredient1: strIngredient1,
            strIngredient2: strIngredient2,
            strIngredient3: strIngredient3,
            strIngredient4: strIngredient4,
            strIngredient5: strIngredient5,
            strIngredient6: strIngredient6,
            strIngredient7: strIngredient7,
            strIngredient8: strIngredient8,
            strIngredient9: strIngredient9,
            strIngredient10: strIngredient10,
            strIngredient11: strIngredient11,
            strIngredient12: strIngredient12,
            strIngredient13: strIngredient13,
            strIngredient14: strIngredient14,
            strIngredient15: strIngredient15,
            strIngredient16: strIngredient16,
            strIngredient17: strIngredient17,
            strIngredient18: strIngredient18,
            strIngredient19: strIngredient19,
            strIngredient20: strIngredient20,
            strMeasure1: strMeasure1,
            strMeasure2: strMeasure2,
            strMeasure3: strMeasure3,
            strMeasure4: strMeasure4,
            strMeasure5: strMeasure5,
            strMeasure6: strMeasure6,
            strMeasure7: strMeasure7,
            strMeasure8: strMeasure8,
            strMeasure9: strMeasure9,
            strMeasure10: strMeasure10,
            strMeasure11: strMeasure11,
            strMeasure12: strMeasure12,
            strMeasure13: strMeasure13,
            strMeasure14: strMeasure14,
            strMeasure15: strMeasure15,
            strMeasure16: strMeasure16,
            strMeasure17: strMeasure17,
            strMeasure18: strMeasure18,
            strMeasure19: strMeasure19,
            strMeasure20: strMeasure20,
            strMealThumb: strMealThumb,
            dateModified: dateModified
        )
    }
}
